[package]
name = "enum-fields"
version = "0.1.0"
authors = ["Heliozoa <dm89132@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
